name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
        
    - name: Build APK
      run: flutter build apk
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk